# Generated by Django 5.0.1 on 2024-02-02 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0003_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-comment_date"]},
        ),
    ]
